"""Shadow Kit command-line interface for public conformance proofs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from shadow_kit.contracts import ContractContext, check_all_post, check_all_pre
from shadow_kit.receipts import (
    ED25519,
    PROJECT_URL,
    generate_ed25519_keypair,
    issue_contract_receipt,
    receipt_hash,
    verify_receipt_chain,
)

DEFAULT_JSON = Path("shadow-kit-proof.json")
DEFAULT_MARKDOWN = Path("SHADOW_KIT_PROOF.md")
EXPECTED_CASES = {
    "unverified-push": "block",
    "capability-denial-without-attempt": "block",
    "verified-push": "allow",
}


def build_conformance_bundle(agent_id: str = "shadow-kit-conformance") -> dict[str, Any]:
    """Run deterministic failure-mode cases and return a public proof bundle."""

    private_key, public_key = generate_ed25519_keypair()
    cases = [
        (
            "unverified-push",
            ContractContext(
                action="git_push",
                files_edited=["src/main.py"],
                response_text="Fixed. Done.",
            ),
            "pre",
            "block",
        ),
        (
            "capability-denial-without-attempt",
            ContractContext(
                action="respond",
                response_text="I can't access that page.",
                tool_calls=[],
                smoke_test_ran=False,
            ),
            "post",
            "block",
        ),
        (
            "verified-push",
            ContractContext(
                action="git_push",
                files_edited=["src/main.py"],
                response_text="12 passed.",
                verification_output="12 passed.",
            ),
            "pre",
            "allow",
        ),
    ]

    receipts: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    previous_hash = ""
    for sequence, (name, ctx, phase, expected) in enumerate(cases, start=1):
        violations = check_all_pre(ctx) if phase == "pre" else check_all_post(ctx)
        receipt = issue_contract_receipt(
            agent_id=agent_id,
            sequence=sequence,
            ctx=ctx,
            violations=violations,
            signing_key=private_key,
            policy_version="shadow-kit-conformance-v1",
            previous_hash=previous_hash,
            signature_algorithm=ED25519,
            verification_key=public_key,
        )
        previous_hash = receipt_hash(receipt)
        receipts.append(receipt)
        results.append(
            {
                "case": name,
                "expected": expected,
                "actual": receipt["decision"],
                "passed": receipt["decision"] == expected,
                "contracts": [v.contract for v in violations],
            }
        )

    verification = verify_receipt_chain(receipts, expected_agent_id=agent_id)
    return {
        "schema_version": "shadow-kit.conformance.v1",
        "project_url": PROJECT_URL,
        "agent_id": agent_id,
        "verification_key": public_key,
        "passed": verification.valid and all(item["passed"] for item in results),
        "results": results,
        "receipts": receipts,
    }


def render_markdown(bundle: dict[str, Any], json_path: Path) -> str:
    status = "PASS" if bundle["passed"] else "FAIL"
    rows = [
        f"| {item['case']} | {item['expected']} | {item['actual']} | "
        f"{'yes' if item['passed'] else 'no'} |"
        for item in bundle["results"]
    ]
    return "\n".join(
        [
            "# Shadow Kit Conformance Proof",
            "",
            f"**Result: {status}**",
            "",
            "| Failure-mode case | Expected | Actual | Passed |",
            "|---|---:|---:|---:|",
            *rows,
            "",
            f"Receipt chain: `{len(bundle['receipts'])}` Ed25519-signed records.",
            f"Verification bundle: [`{json_path.name}`]({json_path.name})",
            "",
            "Verify independently:",
            "",
            "```bash",
            f"shadow-kit verify {json_path.name}",
            "```",
            "",
            f"Generated by [Shadow Kit]({PROJECT_URL}).",
        ]
    )


def prove(json_path: Path, markdown_path: Path, agent_id: str) -> int:
    bundle = build_conformance_bundle(agent_id)
    json_path.write_text(json.dumps(bundle, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    markdown_path.write_text(render_markdown(bundle, json_path) + "\n", encoding="utf-8")
    print(f"{'PASS' if bundle['passed'] else 'FAIL'}: {markdown_path} ({json_path})")
    return 0 if bundle["passed"] else 1


def verify(path: Path) -> int:
    bundle = json.loads(path.read_text(encoding="utf-8"))
    receipts = bundle.get("receipts", [])
    result = verify_receipt_chain(
        receipts,
        expected_agent_id=bundle.get("agent_id"),
    )
    results = bundle.get("results", [])
    cases_pass = (
        len(results) == len(EXPECTED_CASES)
        and len(receipts) == len(EXPECTED_CASES)
        and all(
            item.get("case") in EXPECTED_CASES
            and item.get("expected") == EXPECTED_CASES[item["case"]]
            and item.get("actual") == receipts[index].get("decision")
            and item.get("actual") == EXPECTED_CASES[item["case"]]
            for index, item in enumerate(results)
        )
    )
    valid = result.valid and cases_pass
    print(
        f"{'VALID' if valid else 'INVALID'}: {len(receipts)} receipts, "
        f"sequences {result.first_sequence}-{result.last_sequence}"
    )
    if result.errors:
        print("; ".join(result.errors))
    return 0 if valid else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="shadow-kit")
    subparsers = parser.add_subparsers(dest="command", required=True)

    prove_parser = subparsers.add_parser(
        "prove",
        help="run executable failure-mode cases and emit a public proof bundle",
    )
    prove_parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    prove_parser.add_argument("--markdown", type=Path, default=DEFAULT_MARKDOWN)
    prove_parser.add_argument("--agent-id", default="shadow-kit-conformance")

    verify_parser = subparsers.add_parser(
        "verify",
        help="independently verify an Ed25519 receipt-chain proof bundle",
    )
    verify_parser.add_argument("path", type=Path)

    args = parser.parse_args(argv)
    if args.command == "prove":
        return prove(args.json, args.markdown, args.agent_id)
    return verify(args.path)


if __name__ == "__main__":
    raise SystemExit(main())
