"""Tests for independently verifiable Shadow Kit conformance proofs."""

import json
from pathlib import Path

from shadow_kit.cli import build_conformance_bundle, main, render_markdown
from shadow_kit.receipts import ED25519, verify_receipt_chain


def test_conformance_bundle_is_publicly_verifiable():
    bundle = build_conformance_bundle("test-agent")

    assert bundle["passed"] is True
    assert [item["actual"] for item in bundle["results"]] == ["block", "block", "allow"]
    assert all(receipt["signature_algorithm"] == ED25519 for receipt in bundle["receipts"])
    assert verify_receipt_chain(
        bundle["receipts"],
        expected_agent_id="test-agent",
    ).valid


def test_prove_then_verify_cli(tmp_path):
    json_path = tmp_path / "proof.json"
    markdown_path = tmp_path / "proof.md"

    assert main([
        "prove",
        "--json",
        str(json_path),
        "--markdown",
        str(markdown_path),
    ]) == 0
    assert main(["verify", str(json_path)]) == 0

    bundle = json.loads(json_path.read_text())
    markdown = markdown_path.read_text()
    assert bundle["passed"] is True
    assert "shadow-kit verify proof.json" in markdown
    assert "Generated by [Shadow Kit]" in markdown


def test_verify_rejects_tampered_bundle(tmp_path):
    bundle = build_conformance_bundle()
    bundle["receipts"][0]["decision"] = "allow"
    path = tmp_path / "tampered.json"
    path.write_text(json.dumps(bundle))

    assert main(["verify", str(path)]) == 1


def test_render_markdown_is_commit_ready():
    bundle = build_conformance_bundle()
    markdown = render_markdown(bundle, json_path=Path("proof.json"))

    assert "**Result: PASS**" in markdown
    assert "| unverified-push | block | block | yes |" in markdown
